# Generated by Django 3.2.3 on 2024-07-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
